name: Trigger Dev Webhook on Push

on:
  push:
    branches:
      - dev

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dev Deploy Hook
        env:
          WEBHOOK_URL: ${{ secrets.DEV_DEPLOY_HOOK }}
        run: |
          # Trigger the webhook and capture the HTTP status code
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" -X POST -d '{}' "$WEBHOOK_URL")

          # Check if the request was successful (HTTP status code 200 or 201)
          if [ "$STATUS_CODE" -eq 200 ] || [ "$STATUS_CODE" -eq 201 ]; then
            echo "Webhook triggered successfully with status code $STATUS_CODE."
          else
            echo "Failed to trigger webhook. Status code: $STATUS_CODE."
            exit 1  # Stop the workflow on failure
          fi

      # - name: Post Slack Notification
      #   if: success()
      #   env:
      #     ENVIRONMENT: Development
      #     DEPLOYMENT_SLACK_WEBHOOK: ${{ secrets.VERCEL_SLACK_WEBHOOK }}
      #   run: |
      #     # Send notification to Slack with deployment details
      #     curl -X POST -H 'Content-type: application/json' \
      #     --data '{"text": "Deployment to '${ENVIRONMENT}' has begun for easyshare-web! :rocket:"}' \
      #     "$DEPLOYMENT_SLACK_WEBHOOK"
